// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type CreateDatabaseUsingSSHRequest struct {
	Referer     *string `header:"style=simple,explode=false,name=Referer"`
	RequestBody *string `request:"mediaType=*/*"`
}

type CreateDatabaseUsingSSHResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
}
