// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type DeleteAPIV1ChartChartIDRequest struct {
	ChartID string  `pathParam:"style=simple,explode=false,name=ChartID"`
	Referer *string `header:"style=simple,explode=false,name=Referer"`
}

type DeleteAPIV1ChartChartIDResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
}
