// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type DeleteV1TeamsTeamSlugInvitesInviteIDRequest struct {
	InviteID string `pathParam:"style=simple,explode=false,name=InviteID"`
	TeamSlug string `pathParam:"style=simple,explode=false,name=TeamSlug"`
}

func (o *DeleteV1TeamsTeamSlugInvitesInviteIDRequest) GetInviteID() string {
	if o == nil {
		return ""
	}
	return o.InviteID
}

func (o *DeleteV1TeamsTeamSlugInvitesInviteIDRequest) GetTeamSlug() string {
	if o == nil {
		return ""
	}
	return o.TeamSlug
}

type DeleteV1TeamsTeamSlugInvitesInviteIDResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *DeleteV1TeamsTeamSlugInvitesInviteIDResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *DeleteV1TeamsTeamSlugInvitesInviteIDResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *DeleteV1TeamsTeamSlugInvitesInviteIDResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
