// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type DeleteAPIV1DatasetDatasetIDRequest struct {
	DatasetID string `pathParam:"style=simple,explode=false,name=DatasetID"`
}

type DeleteAPIV1DatasetDatasetIDResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
}
