// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type DeleteV1TeamsTeamSlugPermissionsPermissionNameRequest struct {
	PermissionName string `pathParam:"style=simple,explode=false,name=PermissionName"`
	TeamSlug       string `pathParam:"style=simple,explode=false,name=TeamSlug"`
}

func (o *DeleteV1TeamsTeamSlugPermissionsPermissionNameRequest) GetPermissionName() string {
	if o == nil {
		return ""
	}
	return o.PermissionName
}

func (o *DeleteV1TeamsTeamSlugPermissionsPermissionNameRequest) GetTeamSlug() string {
	if o == nil {
		return ""
	}
	return o.TeamSlug
}

type DeleteV1TeamsTeamSlugPermissionsPermissionNameResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *DeleteV1TeamsTeamSlugPermissionsPermissionNameResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *DeleteV1TeamsTeamSlugPermissionsPermissionNameResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *DeleteV1TeamsTeamSlugPermissionsPermissionNameResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
