// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type DeleteV1TeamsTeamSlugPermissionsPermissionNameRequest struct {
	PermissionName string `pathParam:"style=simple,explode=false,name=PermissionName"`
	TeamSlug       string `pathParam:"style=simple,explode=false,name=TeamSlug"`
}

type DeleteV1TeamsTeamSlugPermissionsPermissionNameResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
}
