// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type DeleteAPIV1AnnotationLayerAnnotationLayerIDRequest struct {
	AnnotationLayerID string  `pathParam:"style=simple,explode=false,name=AnnotationLayerID"`
	Referer           *string `header:"style=simple,explode=false,name=Referer"`
}

type DeleteAPIV1AnnotationLayerAnnotationLayerIDResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
}
