// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type DeleteV1TeamsTeamSlugPermissionsPermissionNameGranteesRequest struct {
	PermissionName string  `pathParam:"style=simple,explode=false,name=PermissionName"`
	TeamSlug       string  `pathParam:"style=simple,explode=false,name=TeamSlug"`
	Referer        *string `header:"style=simple,explode=false,name=referer"`
}

type DeleteV1TeamsTeamSlugPermissionsPermissionNameGranteesResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
}
