// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type DeleteAPIV1AnnotationLayerAnnotationLayerIDAnnotationRequest struct {
	AnnotationLayerID string  `pathParam:"style=simple,explode=false,name=AnnotationLayerID"`
	Referer           *string `header:"style=simple,explode=false,name=Referer"`
	// Comma separated list of Annotation IDs.
	Q *string `queryParam:"style=form,explode=true,name=q"`
}

type DeleteAPIV1AnnotationLayerAnnotationLayerIDAnnotationResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
}
