// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type DeleteV1TeamsTeamSlugPermissionsPermissionNameGranteesRequest struct {
	PermissionName string  `pathParam:"style=simple,explode=false,name=PermissionName"`
	TeamSlug       string  `pathParam:"style=simple,explode=false,name=TeamSlug"`
	Referer        *string `header:"style=simple,explode=false,name=referer"`
}

func (o *DeleteV1TeamsTeamSlugPermissionsPermissionNameGranteesRequest) GetPermissionName() string {
	if o == nil {
		return ""
	}
	return o.PermissionName
}

func (o *DeleteV1TeamsTeamSlugPermissionsPermissionNameGranteesRequest) GetTeamSlug() string {
	if o == nil {
		return ""
	}
	return o.TeamSlug
}

func (o *DeleteV1TeamsTeamSlugPermissionsPermissionNameGranteesRequest) GetReferer() *string {
	if o == nil {
		return nil
	}
	return o.Referer
}

type DeleteV1TeamsTeamSlugPermissionsPermissionNameGranteesResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *DeleteV1TeamsTeamSlugPermissionsPermissionNameGranteesResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *DeleteV1TeamsTeamSlugPermissionsPermissionNameGranteesResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *DeleteV1TeamsTeamSlugPermissionsPermissionNameGranteesResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
