// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type DeleteAPIV1AnnotationLayerRequest struct {
	Referer *string `header:"style=simple,explode=false,name=Referer"`
	// Comma separated list of Annotation Layer IDs.
	Q *string `queryParam:"style=form,explode=true,name=q"`
}

type DeleteAPIV1AnnotationLayerResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}
