// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type GetAPIV1AnnotationLayerAnnotationLayerIDAnnotationRequest struct {
	AnnotationLayerID string `pathParam:"style=simple,explode=false,name=AnnotationLayerID"`
}

type GetAPIV1AnnotationLayerAnnotationLayerIDAnnotationResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
}
