// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type GetAPIV1DatabaseExportRequest struct {
	// Comma separated list of database connection IDs.
	Q *string `queryParam:"style=form,explode=true,name=q"`
}

type GetAPIV1DatabaseExportResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}
