// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type GetAPIV1AnnotationLayerAnnotationLayerIDRequest struct {
	AnnotationLayerID string `pathParam:"style=simple,explode=false,name=AnnotationLayerID"`
}

type GetAPIV1AnnotationLayerAnnotationLayerIDResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}
