// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type GetAPIV1ChartChartIDDataRequest struct {
	ChartID string `pathParam:"style=simple,explode=false,name=ChartID"`
}

type GetAPIV1ChartChartIDDataResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
}
