// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type GetAPIV1ChartExportRequest struct {
	Referer *string `header:"style=simple,explode=false,name=Referer"`
	// Comma separated list of Chart IDs.
	Q *string `queryParam:"style=form,explode=true,name=q"`
}

func (o *GetAPIV1ChartExportRequest) GetReferer() *string {
	if o == nil {
		return nil
	}
	return o.Referer
}

func (o *GetAPIV1ChartExportRequest) GetQ() *string {
	if o == nil {
		return nil
	}
	return o.Q
}

type GetAPIV1ChartExportResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *GetAPIV1ChartExportResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GetAPIV1ChartExportResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GetAPIV1ChartExportResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
