// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type GetAPIV1ChartExportRequest struct {
	Referer *string `header:"style=simple,explode=false,name=Referer"`
	// Comma separated list of Chart IDs.
	Q *string `queryParam:"style=form,explode=true,name=q"`
}

type GetAPIV1ChartExportResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
}
