// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type GetAPIV1ChartChartIDRequest struct {
	ChartID string `pathParam:"style=simple,explode=false,name=ChartID"`
}

type GetAPIV1ChartChartIDResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
}
