// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type GetAPIV1ChartChartIDCacheScreenshotRequest struct {
	ChartID string `pathParam:"style=simple,explode=false,name=ChartID"`
}

func (o *GetAPIV1ChartChartIDCacheScreenshotRequest) GetChartID() string {
	if o == nil {
		return ""
	}
	return o.ChartID
}

type GetAPIV1ChartChartIDCacheScreenshotResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *GetAPIV1ChartChartIDCacheScreenshotResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GetAPIV1ChartChartIDCacheScreenshotResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GetAPIV1ChartChartIDCacheScreenshotResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
