// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type GetAPIV1AssetsExportRequest struct {
}

type GetAPIV1AssetsExportResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
}
