// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type GetAPIV1DatasetRequest struct {
}

type GetAPIV1DatasetResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
}
