// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type GetAPIV1DashboardExportRequest struct {
	// Comma separated list of Dashboard IDs.
	Q *string `queryParam:"style=form,explode=true,name=q"`
}

type GetAPIV1DashboardExportResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
}
