// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type GetAPIV1ReportRequest struct {
	// Used to filter results to include only `Reports`.
	// Pagination and page size  are also controlled by this parameter (max page size = 100).
	Q *string `queryParam:"style=form,explode=true,name=q"`
}

type GetAPIV1ReportResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
}
