// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type GetAPIV1DatabaseExportRequest struct {
	// Comma separated list of database connection IDs.
	Q *string `queryParam:"style=form,explode=true,name=q"`
}

type GetAPIV1DatabaseExportResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
}
