// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type GetAPIV1ReportRequest struct {
	// Used to filter results to include only `Reports`.
	// Pagination and page size  are also controlled by this parameter (max page size = 100).
	Q *string `queryParam:"style=form,explode=true,name=q"`
}

func (o *GetAPIV1ReportRequest) GetQ() *string {
	if o == nil {
		return nil
	}
	return o.Q
}

type GetAPIV1ReportResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *GetAPIV1ReportResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GetAPIV1ReportResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GetAPIV1ReportResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
