// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type GetV1TeamsRequest struct {
}

type GetV1TeamsResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
}
