// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type GetV1TeamsTeamSlugWorkspacesWorkspaceIDMembershipsRequest struct {
	TeamSlug    string `pathParam:"style=simple,explode=false,name=TeamSlug"`
	WorkspaceID string `pathParam:"style=simple,explode=false,name=WorkspaceID"`
}

type GetV1TeamsTeamSlugWorkspacesWorkspaceIDMembershipsResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
}
