// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type GetV1TeamsTeamSlugWorkspacesWorkspaceIDMembershipsRequest struct {
	TeamSlug    string `pathParam:"style=simple,explode=false,name=TeamSlug"`
	WorkspaceID string `pathParam:"style=simple,explode=false,name=WorkspaceID"`
}

func (o *GetV1TeamsTeamSlugWorkspacesWorkspaceIDMembershipsRequest) GetTeamSlug() string {
	if o == nil {
		return ""
	}
	return o.TeamSlug
}

func (o *GetV1TeamsTeamSlugWorkspacesWorkspaceIDMembershipsRequest) GetWorkspaceID() string {
	if o == nil {
		return ""
	}
	return o.WorkspaceID
}

type GetV1TeamsTeamSlugWorkspacesWorkspaceIDMembershipsResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *GetV1TeamsTeamSlugWorkspacesWorkspaceIDMembershipsResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GetV1TeamsTeamSlugWorkspacesWorkspaceIDMembershipsResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GetV1TeamsTeamSlugWorkspacesWorkspaceIDMembershipsResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
