// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type PatchV1TeamsTeamSlugPermissionsPermissionNameRequestBody struct {
}

type PatchV1TeamsTeamSlugPermissionsPermissionNameRequest struct {
	PermissionName string                                                    `pathParam:"style=simple,explode=false,name=PermissionName"`
	RequestBody    *PatchV1TeamsTeamSlugPermissionsPermissionNameRequestBody `request:"mediaType=application/json"`
	TeamSlug       string                                                    `pathParam:"style=simple,explode=false,name=TeamSlug"`
}

type PatchV1TeamsTeamSlugPermissionsPermissionNameResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}
