// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type PatchV1TeamsTeamSlugPermissionsPermissionNameRequestBody struct {
}

type PatchV1TeamsTeamSlugPermissionsPermissionNameRequest struct {
	PermissionName string                                                    `pathParam:"style=simple,explode=false,name=PermissionName"`
	RequestBody    *PatchV1TeamsTeamSlugPermissionsPermissionNameRequestBody `request:"mediaType=application/json"`
	TeamSlug       string                                                    `pathParam:"style=simple,explode=false,name=TeamSlug"`
}

func (o *PatchV1TeamsTeamSlugPermissionsPermissionNameRequest) GetPermissionName() string {
	if o == nil {
		return ""
	}
	return o.PermissionName
}

func (o *PatchV1TeamsTeamSlugPermissionsPermissionNameRequest) GetRequestBody() *PatchV1TeamsTeamSlugPermissionsPermissionNameRequestBody {
	if o == nil {
		return nil
	}
	return o.RequestBody
}

func (o *PatchV1TeamsTeamSlugPermissionsPermissionNameRequest) GetTeamSlug() string {
	if o == nil {
		return ""
	}
	return o.TeamSlug
}

type PatchV1TeamsTeamSlugPermissionsPermissionNameResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *PatchV1TeamsTeamSlugPermissionsPermissionNameResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *PatchV1TeamsTeamSlugPermissionsPermissionNameResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *PatchV1TeamsTeamSlugPermissionsPermissionNameResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
