// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type PostAPIV1DashboardDashboardIDPermalinkRequestBody struct {
}

type PostAPIV1DashboardDashboardIDPermalinkRequest struct {
	DashboardID string                                             `pathParam:"style=simple,explode=false,name=DashboardID"`
	Referer     *string                                            `header:"style=simple,explode=false,name=Referer"`
	RequestBody *PostAPIV1DashboardDashboardIDPermalinkRequestBody `request:"mediaType=application/json"`
}

type PostAPIV1DashboardDashboardIDPermalinkResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
}
