// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type PostAPIV1ChartImportRequestBodyFormData struct {
	Content  []byte `multipartForm:"content"`
	FormData string `multipartForm:"name=formData"`
}

type PostAPIV1ChartImportRequestBody struct {
	FormData  *PostAPIV1ChartImportRequestBodyFormData `multipartForm:"file"`
	Overwrite *bool                                    `multipartForm:"name=overwrite"`
	Passwords *string                                  `multipartForm:"name=passwords"`
}

type PostAPIV1ChartImportRequest struct {
	Referer     *string                          `header:"style=simple,explode=false,name=Referer"`
	RequestBody *PostAPIV1ChartImportRequestBody `request:"mediaType=multipart/form-data"`
}

type PostAPIV1ChartImportResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
}
