// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type PostAPIV1DatasetRequestBody struct {
}

type PostAPIV1DatasetRequest struct {
	RequestBody *PostAPIV1DatasetRequestBody `request:"mediaType=application/json"`
}

type PostAPIV1DatasetResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
}
