// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type PostAPIV1DatabaseRequestBody struct {
}

type PostAPIV1DatabaseRequest struct {
	Referer     *string                       `header:"style=simple,explode=false,name=Referer"`
	RequestBody *PostAPIV1DatabaseRequestBody `request:"mediaType=application/json"`
}

type PostAPIV1DatabaseResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
}
