// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type PostV1TeamsTeamSlugInvitesRequestBody struct {
}

type PostV1TeamsTeamSlugInvitesRequest struct {
	RequestBody *PostV1TeamsTeamSlugInvitesRequestBody `request:"mediaType=application/json"`
	TeamSlug    string                                 `pathParam:"style=simple,explode=false,name=TeamSlug"`
}

type PostV1TeamsTeamSlugInvitesResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
}
