// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type PostAPIV1ChartRequestBody struct {
}

type PostAPIV1ChartRequest struct {
	RequestBody *PostAPIV1ChartRequestBody `request:"mediaType=application/json"`
}

type PostAPIV1ChartResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
}
