// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type PostV1AuthRequestBody struct {
}

type PostV1AuthRequest struct {
	RequestBody *PostV1AuthRequestBody `request:"mediaType=application/json"`
}

type PostV1AuthResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}
