// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type PostV1TeamsTeamSlugPermissionsRequestBody struct {
}

type PostV1TeamsTeamSlugPermissionsRequest struct {
	RequestBody *PostV1TeamsTeamSlugPermissionsRequestBody `request:"mediaType=application/json"`
	TeamSlug    string                                     `pathParam:"style=simple,explode=false,name=TeamSlug"`
}

type PostV1TeamsTeamSlugPermissionsResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
}
