// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type PostAPIV1TeamsTeamSlugWorkspacesWorkspaceSlugGuestTokenRequestBody struct {
}

type PostAPIV1TeamsTeamSlugWorkspacesWorkspaceSlugGuestTokenRequest struct {
	RequestBody   *PostAPIV1TeamsTeamSlugWorkspacesWorkspaceSlugGuestTokenRequestBody `request:"mediaType=application/json"`
	TeamSlug      string                                                              `pathParam:"style=simple,explode=false,name=TeamSlug"`
	WorkspaceSlug string                                                              `pathParam:"style=simple,explode=false,name=WorkspaceSlug"`
}

type PostAPIV1TeamsTeamSlugWorkspacesWorkspaceSlugGuestTokenResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}
