// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type PostV1TeamsTeamSlugInvitesManyRequestBody struct {
}

type PostV1TeamsTeamSlugInvitesManyRequest struct {
	RequestBody *PostV1TeamsTeamSlugInvitesManyRequestBody `request:"mediaType=application/json"`
	TeamSlug    string                                     `pathParam:"style=simple,explode=false,name=TeamSlug"`
}

type PostV1TeamsTeamSlugInvitesManyResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
}
