// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type PostAPIV1DatabaseImportRequestBodyFormData struct {
	Content  []byte `multipartForm:"content"`
	FormData string `multipartForm:"name=formData"`
}

type PostAPIV1DatabaseImportRequestBody struct {
	FormData  *PostAPIV1DatabaseImportRequestBodyFormData `multipartForm:"file"`
	Overwrite *bool                                       `multipartForm:"name=overwrite"`
	Passwords *string                                     `multipartForm:"name=passwords"`
}

type PostAPIV1DatabaseImportRequest struct {
	Referer     *string                             `header:"style=simple,explode=false,name=Referer"`
	RequestBody *PostAPIV1DatabaseImportRequestBody `request:"mediaType=multipart/form-data"`
}

type PostAPIV1DatabaseImportResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
}
