// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type PostAPIV1DashboardRequestBody struct {
}

type PostAPIV1DashboardRequest struct {
	Referer     *string                        `header:"style=simple,explode=false,name=Referer"`
	RequestBody *PostAPIV1DashboardRequestBody `request:"mediaType=application/json"`
}

type PostAPIV1DashboardResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
}
