// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type PostAPIV1DashboardImportRequestBodyFormData struct {
	Content  []byte `multipartForm:"content"`
	FormData string `multipartForm:"name=formData"`
}

type PostAPIV1DashboardImportRequestBody struct {
	FormData  *PostAPIV1DashboardImportRequestBodyFormData `multipartForm:"file"`
	Overwrite *bool                                        `multipartForm:"name=overwrite"`
	Passwords *string                                      `multipartForm:"name=passwords"`
}

type PostAPIV1DashboardImportRequest struct {
	Referer     *string                              `header:"style=simple,explode=false,name=Referer"`
	RequestBody *PostAPIV1DashboardImportRequestBody `request:"mediaType=multipart/form-data"`
}

type PostAPIV1DashboardImportResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
}
