// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type PostAPIV1AnnotationLayerAnnotationLayerIDAnnotationRequestBody struct {
}

type PostAPIV1AnnotationLayerAnnotationLayerIDAnnotationRequest struct {
	AnnotationLayerID string                                                          `pathParam:"style=simple,explode=false,name=AnnotationLayerID"`
	Referer           *string                                                         `header:"style=simple,explode=false,name=Referer"`
	RequestBody       *PostAPIV1AnnotationLayerAnnotationLayerIDAnnotationRequestBody `request:"mediaType=application/json"`
}

type PostAPIV1AnnotationLayerAnnotationLayerIDAnnotationResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
}
