// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type PostV1TeamsTeamSlugInvitesManyRequestBody struct {
}

type PostV1TeamsTeamSlugInvitesManyRequest struct {
	RequestBody *PostV1TeamsTeamSlugInvitesManyRequestBody `request:"mediaType=application/json"`
	TeamSlug    string                                     `pathParam:"style=simple,explode=false,name=TeamSlug"`
}

func (o *PostV1TeamsTeamSlugInvitesManyRequest) GetRequestBody() *PostV1TeamsTeamSlugInvitesManyRequestBody {
	if o == nil {
		return nil
	}
	return o.RequestBody
}

func (o *PostV1TeamsTeamSlugInvitesManyRequest) GetTeamSlug() string {
	if o == nil {
		return ""
	}
	return o.TeamSlug
}

type PostV1TeamsTeamSlugInvitesManyResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *PostV1TeamsTeamSlugInvitesManyResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *PostV1TeamsTeamSlugInvitesManyResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *PostV1TeamsTeamSlugInvitesManyResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
