// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type PostV1TeamsTeamSlugWorkspacesRequestBody struct {
}

type PostV1TeamsTeamSlugWorkspacesRequest struct {
	RequestBody *PostV1TeamsTeamSlugWorkspacesRequestBody `request:"mediaType=application/json"`
	TeamSlug    string                                    `pathParam:"style=simple,explode=false,name=TeamSlug"`
}

func (o *PostV1TeamsTeamSlugWorkspacesRequest) GetRequestBody() *PostV1TeamsTeamSlugWorkspacesRequestBody {
	if o == nil {
		return nil
	}
	return o.RequestBody
}

func (o *PostV1TeamsTeamSlugWorkspacesRequest) GetTeamSlug() string {
	if o == nil {
		return ""
	}
	return o.TeamSlug
}

type PostV1TeamsTeamSlugWorkspacesResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *PostV1TeamsTeamSlugWorkspacesResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *PostV1TeamsTeamSlugWorkspacesResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *PostV1TeamsTeamSlugWorkspacesResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
