// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type PostAPIV1TeamsTeamSlugWorkspacesWorkspaceSlugGuestTokenRequestBody struct {
}

type PostAPIV1TeamsTeamSlugWorkspacesWorkspaceSlugGuestTokenRequest struct {
	RequestBody   *PostAPIV1TeamsTeamSlugWorkspacesWorkspaceSlugGuestTokenRequestBody `request:"mediaType=application/json"`
	TeamSlug      string                                                              `pathParam:"style=simple,explode=false,name=TeamSlug"`
	WorkspaceSlug string                                                              `pathParam:"style=simple,explode=false,name=WorkspaceSlug"`
}

type PostAPIV1TeamsTeamSlugWorkspacesWorkspaceSlugGuestTokenResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
}
