// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type PostAPIV1SqllabExecuteRequestBody struct {
}

type PostAPIV1SqllabExecuteRequest struct {
	Referer     *string                            `header:"style=simple,explode=false,name=Referer"`
	RequestBody *PostAPIV1SqllabExecuteRequestBody `request:"mediaType=application/json"`
}

type PostAPIV1SqllabExecuteResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
}
