// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type PostAPIV1ChartImportRequestBodyFormData struct {
	Content  []byte `multipartForm:"content"`
	FormData string `multipartForm:"name=formData"`
}

func (o *PostAPIV1ChartImportRequestBodyFormData) GetContent() []byte {
	if o == nil {
		return []byte{}
	}
	return o.Content
}

func (o *PostAPIV1ChartImportRequestBodyFormData) GetFormData() string {
	if o == nil {
		return ""
	}
	return o.FormData
}

type PostAPIV1ChartImportRequestBody struct {
	FormData  *PostAPIV1ChartImportRequestBodyFormData `multipartForm:"file"`
	Overwrite *bool                                    `multipartForm:"name=overwrite"`
	Passwords *string                                  `multipartForm:"name=passwords"`
}

func (o *PostAPIV1ChartImportRequestBody) GetFormData() *PostAPIV1ChartImportRequestBodyFormData {
	if o == nil {
		return nil
	}
	return o.FormData
}

func (o *PostAPIV1ChartImportRequestBody) GetOverwrite() *bool {
	if o == nil {
		return nil
	}
	return o.Overwrite
}

func (o *PostAPIV1ChartImportRequestBody) GetPasswords() *string {
	if o == nil {
		return nil
	}
	return o.Passwords
}

type PostAPIV1ChartImportRequest struct {
	Referer     *string                          `header:"style=simple,explode=false,name=Referer"`
	RequestBody *PostAPIV1ChartImportRequestBody `request:"mediaType=multipart/form-data"`
}

func (o *PostAPIV1ChartImportRequest) GetReferer() *string {
	if o == nil {
		return nil
	}
	return o.Referer
}

func (o *PostAPIV1ChartImportRequest) GetRequestBody() *PostAPIV1ChartImportRequestBody {
	if o == nil {
		return nil
	}
	return o.RequestBody
}

type PostAPIV1ChartImportResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *PostAPIV1ChartImportResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *PostAPIV1ChartImportResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *PostAPIV1ChartImportResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
