// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type PostV1AuthRequestBody struct {
}

type PostV1AuthRequest struct {
	RequestBody *PostV1AuthRequestBody `request:"mediaType=application/json"`
}

type PostV1AuthResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
}
