// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type PostAPIV1DatasetImportRequestBodyFormData struct {
	Content  []byte `multipartForm:"content"`
	FormData string `multipartForm:"name=formData"`
}

type PostAPIV1DatasetImportRequestBody struct {
	FormData  *PostAPIV1DatasetImportRequestBodyFormData `multipartForm:"file"`
	Overwrite *bool                                      `multipartForm:"name=overwrite"`
	Passwords *string                                    `multipartForm:"name=passwords"`
}

type PostAPIV1DatasetImportRequest struct {
	Referer     *string                            `header:"style=simple,explode=false,name=Referer"`
	RequestBody *PostAPIV1DatasetImportRequestBody `request:"mediaType=multipart/form-data"`
}

type PostAPIV1DatasetImportResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
}
