// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type PostAPIV1ReportRequestBody struct {
}

type PostAPIV1ReportRequest struct {
	Referer     *string                     `header:"style=simple,explode=false,name=Referer"`
	RequestBody *PostAPIV1ReportRequestBody `request:"mediaType=application/json"`
}

type PostAPIV1ReportResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}
