// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type PostAPIV1AssetsImportRequestBodyBundle struct {
	Bundle  string `multipartForm:"name=bundle"`
	Content []byte `multipartForm:"content"`
}

type PostAPIV1AssetsImportRequestBody struct {
	Bundle    *PostAPIV1AssetsImportRequestBodyBundle `multipartForm:"file"`
	Passwords *string                                 `multipartForm:"name=passwords"`
}

type PostAPIV1AssetsImportRequest struct {
	RequestBody *PostAPIV1AssetsImportRequestBody `request:"mediaType=multipart/form-data"`
}

type PostAPIV1AssetsImportResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}
