// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type PutAPIV1AnnotationLayerAnnotationLayerIDRequestBody struct {
}

type PutAPIV1AnnotationLayerAnnotationLayerIDRequest struct {
	AnnotationLayerID string                                               `pathParam:"style=simple,explode=false,name=AnnotationLayerID"`
	Referer           *string                                              `header:"style=simple,explode=false,name=Referer"`
	RequestBody       *PutAPIV1AnnotationLayerAnnotationLayerIDRequestBody `request:"mediaType=application/json"`
}

func (o *PutAPIV1AnnotationLayerAnnotationLayerIDRequest) GetAnnotationLayerID() string {
	if o == nil {
		return ""
	}
	return o.AnnotationLayerID
}

func (o *PutAPIV1AnnotationLayerAnnotationLayerIDRequest) GetReferer() *string {
	if o == nil {
		return nil
	}
	return o.Referer
}

func (o *PutAPIV1AnnotationLayerAnnotationLayerIDRequest) GetRequestBody() *PutAPIV1AnnotationLayerAnnotationLayerIDRequestBody {
	if o == nil {
		return nil
	}
	return o.RequestBody
}

type PutAPIV1AnnotationLayerAnnotationLayerIDResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *PutAPIV1AnnotationLayerAnnotationLayerIDResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *PutAPIV1AnnotationLayerAnnotationLayerIDResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *PutAPIV1AnnotationLayerAnnotationLayerIDResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
