// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type PutAPIV1AnnotationLayerAnnotationLayerIDAnnotationAnnotationIDRequestBody struct {
}

type PutAPIV1AnnotationLayerAnnotationLayerIDAnnotationAnnotationIDRequest struct {
	AnnotationID      string                                                                     `pathParam:"style=simple,explode=false,name=AnnotationID"`
	AnnotationLayerID string                                                                     `pathParam:"style=simple,explode=false,name=AnnotationLayerID"`
	Referer           *string                                                                    `header:"style=simple,explode=false,name=Referer"`
	RequestBody       *PutAPIV1AnnotationLayerAnnotationLayerIDAnnotationAnnotationIDRequestBody `request:"mediaType=application/json"`
}

func (o *PutAPIV1AnnotationLayerAnnotationLayerIDAnnotationAnnotationIDRequest) GetAnnotationID() string {
	if o == nil {
		return ""
	}
	return o.AnnotationID
}

func (o *PutAPIV1AnnotationLayerAnnotationLayerIDAnnotationAnnotationIDRequest) GetAnnotationLayerID() string {
	if o == nil {
		return ""
	}
	return o.AnnotationLayerID
}

func (o *PutAPIV1AnnotationLayerAnnotationLayerIDAnnotationAnnotationIDRequest) GetReferer() *string {
	if o == nil {
		return nil
	}
	return o.Referer
}

func (o *PutAPIV1AnnotationLayerAnnotationLayerIDAnnotationAnnotationIDRequest) GetRequestBody() *PutAPIV1AnnotationLayerAnnotationLayerIDAnnotationAnnotationIDRequestBody {
	if o == nil {
		return nil
	}
	return o.RequestBody
}

type PutAPIV1AnnotationLayerAnnotationLayerIDAnnotationAnnotationIDResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *PutAPIV1AnnotationLayerAnnotationLayerIDAnnotationAnnotationIDResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *PutAPIV1AnnotationLayerAnnotationLayerIDAnnotationAnnotationIDResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *PutAPIV1AnnotationLayerAnnotationLayerIDAnnotationAnnotationIDResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
