// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type PutAPIV1ReportAlertIDORReportIDRequestBody struct {
}

type PutAPIV1ReportAlertIDORReportIDRequest struct {
	RequestBody *PutAPIV1ReportAlertIDORReportIDRequestBody `request:"mediaType=application/json"`
}

type PutAPIV1ReportAlertIDORReportIDResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
}
