// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type PutAPIV1ReportAlertIDORReportIDRequestBody struct {
}

type PutAPIV1ReportAlertIDORReportIDRequest struct {
	RequestBody *PutAPIV1ReportAlertIDORReportIDRequestBody `request:"mediaType=application/json"`
}

type PutAPIV1ReportAlertIDORReportIDResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}
