// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type PutAPIV1DatabaseDatabaseIDRequest struct {
	DatabaseID  string  `pathParam:"style=simple,explode=false,name=DatabaseID"`
	RequestBody *string `request:"mediaType=*/*"`
}

type PutAPIV1DatabaseDatabaseIDResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
}
