// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type PutAPIV1AnnotationLayerAnnotationLayerIDRequestBody struct {
}

type PutAPIV1AnnotationLayerAnnotationLayerIDRequest struct {
	AnnotationLayerID string                                               `pathParam:"style=simple,explode=false,name=AnnotationLayerID"`
	Referer           *string                                              `header:"style=simple,explode=false,name=Referer"`
	RequestBody       *PutAPIV1AnnotationLayerAnnotationLayerIDRequestBody `request:"mediaType=application/json"`
}

type PutAPIV1AnnotationLayerAnnotationLayerIDResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
}
