// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type PutAPIV1DashboardDashboardIDRequest struct {
	DashboardID string  `pathParam:"style=simple,explode=false,name=DashboardID"`
	Referer     *string `header:"style=simple,explode=false,name=Referer"`
	RequestBody *string `request:"mediaType=*/*"`
}

type PutAPIV1DashboardDashboardIDResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
}
