// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type PutAPIV1DatasetDatasetIDRefreshRequestBody struct {
}

type PutAPIV1DatasetDatasetIDRefreshRequest struct {
	DatasetID   string                                      `pathParam:"style=simple,explode=false,name=DatasetID"`
	Referer     *string                                     `header:"style=simple,explode=false,name=Referer"`
	RequestBody *PutAPIV1DatasetDatasetIDRefreshRequestBody `request:"mediaType=application/json"`
}

type PutAPIV1DatasetDatasetIDRefreshResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
}
