// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type PutV1TeamsTeamSlugRequestBody struct {
}

type PutV1TeamsTeamSlugRequest struct {
	RequestBody *PutV1TeamsTeamSlugRequestBody `request:"mediaType=application/json"`
	TeamSlug    string                         `pathParam:"style=simple,explode=false,name=TeamSlug"`
}

type PutV1TeamsTeamSlugResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
}
