// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type PutV1TeamsTeamSlugWorkspacesWorkspaceIDMembershipRequestBody struct {
}

type PutV1TeamsTeamSlugWorkspacesWorkspaceIDMembershipRequest struct {
	RequestBody *PutV1TeamsTeamSlugWorkspacesWorkspaceIDMembershipRequestBody `request:"mediaType=application/json"`
	TeamSlug    string                                                        `pathParam:"style=simple,explode=false,name=TeamSlug"`
	WorkspaceID string                                                        `pathParam:"style=simple,explode=false,name=WorkspaceID"`
}

type PutV1TeamsTeamSlugWorkspacesWorkspaceIDMembershipResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}
